import type { Workspace } from "@/lib/domain"

export const demoWorkspace: Workspace = {
  mode: "demo",
  goals: [
    {
      id: "goal-running",
      title: "Пробежать первый полумарафон",
      description:
        "Подготовиться и пробежать 21.1 км без остановок, наращивая объём постепенно и без травм.",
      status: "active",
      targetDate: "2026-09-20",
      progressPercent: 45,
      clarifiedContext: {
        baseline: "сейчас комфортно бегаю 3 км",
        success: "21.1 км без остановок на целевом темпе",
        constraints: "3 тренировки в неделю, выходной для восстановления",
      },
    },
    {
      id: "goal-ielts",
      title: "Сдать IELTS на 7.0",
      description:
        "Поднять английский с B2 до уверенного 7.0 overall, подтянув самую слабую секцию Writing.",
      status: "active",
      targetDate: "2026-10-15",
      progressPercent: 30,
      clarifiedContext: {
        current: "уровень B2",
        target: "7.0 overall",
        weakest: "Writing Task 2",
      },
    },
    {
      id: "goal-savings",
      title: "Сформировать подушку безопасности на 6 месяцев",
      description:
        "Накопить резерв в размере шести месячных расходов через регулярный автоперевод части дохода.",
      status: "active",
      targetDate: "2026-12-31",
      progressPercent: 60,
      clarifiedContext: {
        target: "6× месячных расходов",
        channel: "автоперевод 20% дохода на накопительный счёт",
      },
    },
    {
      id: "goal-petproject",
      title: "Запустить лендинг пет-проекта",
      description:
        "Проверить спрос на нишевый трекер привычек: собрать лендинг, подключить аналитику и форму заявок.",
      status: "active",
      targetDate: "2026-08-30",
      progressPercent: 50,
      clarifiedContext: {
        hypothesis: "есть спрос на нишевый трекер привычек",
        audience: "продакт-менеджеры и фрилансеры",
      },
    },
  ],
  tasks: [
    {
      id: "task-run-base",
      goalId: "goal-running",
      title: "Базовый объём 15 км в неделю",
      notes: "Три лёгкие пробежки, темп разговорный.",
      effort: "L",
      dueDate: "2026-06-21",
      status: "doing",
      sortOrder: 10,
    },
    {
      id: "task-run-intervals",
      goalId: "goal-running",
      title: "Интервальная тренировка по вторникам",
      notes: "6×400 м с восстановлением трусцой.",
      effort: "M",
      dueDate: "2026-06-23",
      status: "todo",
      sortOrder: 20,
    },
    {
      id: "task-run-long",
      goalId: "goal-running",
      title: "Длинная пробежка по воскресеньям +1 км/нед",
      notes: "Постепенно довести длинную до 18 км.",
      effort: "M",
      dueDate: "2026-06-28",
      status: "doing",
      sortOrder: 30,
    },
    {
      id: "task-run-gear",
      goalId: "goal-running",
      title: "Подобрать кроссовки и план питания",
      notes: "Беговые кроссовки по пронации, гели на длинную.",
      effort: "S",
      dueDate: "2026-06-15",
      status: "done",
      sortOrder: 40,
    },
    {
      id: "task-run-10k",
      goalId: "goal-running",
      title: "Контрольный забег на 10 км",
      notes: "Оценить целевой темп за месяц до старта.",
      effort: "M",
      dueDate: "2026-08-23",
      status: "todo",
      sortOrder: 50,
    },
    {
      id: "task-ielts-mock1",
      goalId: "goal-ielts",
      title: "Пробный тест и разбор слабых секций",
      notes: "Зафиксировать базовый балл по всем секциям.",
      effort: "M",
      dueDate: "2026-06-14",
      status: "done",
      sortOrder: 10,
    },
    {
      id: "task-ielts-speaking",
      goalId: "goal-ielts",
      title: "Speaking-партнёр 2 раза в неделю",
      notes: "Разговорная практика по part 2/3 с обратной связью.",
      effort: "M",
      dueDate: "2026-06-24",
      status: "doing",
      sortOrder: 20,
    },
    {
      id: "task-ielts-writing",
      goalId: "goal-ielts",
      title: "20 эссе Writing Task 2 с фидбеком",
      notes: "Шаблоны аргументации и работа над когезией.",
      effort: "L",
      dueDate: "2026-09-30",
      status: "todo",
      sortOrder: 30,
    },
    {
      id: "task-ielts-anki",
      goalId: "goal-ielts",
      title: "Anki: 50 academic words в неделю",
      notes: "Колода Academic Word List, ежедневные повторения.",
      effort: "S",
      dueDate: "2026-06-22",
      status: "doing",
      sortOrder: 40,
    },
    {
      id: "task-ielts-final-mock",
      goalId: "goal-ielts",
      title: "Mock-экзамен за две недели до даты",
      notes: "Полный прогон по таймингу реального экзамена.",
      effort: "M",
      dueDate: "2026-10-01",
      status: "todo",
      sortOrder: 50,
    },
    {
      id: "task-savings-budget",
      goalId: "goal-savings",
      title: "Свести бюджет за последние 3 месяца",
      notes: "Понять реальные месячные расходы и категории.",
      effort: "M",
      dueDate: "2026-06-10",
      status: "done",
      sortOrder: 10,
    },
    {
      id: "task-savings-autopay",
      goalId: "goal-savings",
      title: "Настроить автоперевод 20% дохода",
      notes: "В день зарплаты на отдельный накопительный счёт.",
      effort: "S",
      dueDate: "2026-06-12",
      status: "done",
      sortOrder: 20,
    },
    {
      id: "task-savings-cut",
      goalId: "goal-savings",
      title: "Сократить 3 категории расходов",
      notes: "Подписки, доставка еды, импульсивные покупки.",
      effort: "M",
      dueDate: "2026-06-30",
      status: "doing",
      sortOrder: 30,
    },
    {
      id: "task-savings-account",
      goalId: "goal-savings",
      title: "Открыть отдельный счёт под резерв",
      notes: "Накопительный счёт с процентом на остаток.",
      effort: "S",
      dueDate: "2026-06-08",
      status: "done",
      sortOrder: 40,
    },
    {
      id: "task-pet-hypothesis",
      goalId: "goal-petproject",
      title: "Сформулировать гипотезу и ЦА",
      notes: "Проблема, сегмент, ценностное предложение.",
      effort: "S",
      dueDate: "2026-06-05",
      status: "done",
      sortOrder: 10,
    },
    {
      id: "task-pet-landing",
      goalId: "goal-petproject",
      title: "Собрать прототип лендинга",
      notes: "Hero, оффер, секция фич, CTA на форму.",
      effort: "M",
      dueDate: "2026-07-05",
      status: "doing",
      sortOrder: 20,
    },
    {
      id: "task-pet-analytics",
      goalId: "goal-petproject",
      title: "Подключить аналитику и форму заявок",
      notes: "События целей и сбор email в одну таблицу.",
      effort: "M",
      dueDate: "2026-07-12",
      status: "todo",
      sortOrder: 30,
    },
    {
      id: "task-pet-ads",
      goalId: "goal-petproject",
      title: "Тестовый таргет на 10 000 ₽",
      notes: "Проверить CPL и конверсию в заявку.",
      effort: "M",
      dueDate: "2026-07-20",
      status: "todo",
      sortOrder: 40,
    },
    {
      id: "task-pet-leads",
      goalId: "goal-petproject",
      title: "Собрать 50 заявок и сделать выводы",
      notes: "Решение go/no-go по дальнейшей разработке.",
      effort: "L",
      dueDate: "2026-08-25",
      status: "todo",
      sortOrder: 50,
    },
  ],
  aiSessions: [
    {
      id: "session-clarify",
      goalId: "goal-running",
      type: "clarify",
      model: "google/gemini-2.5-flash-lite",
      status: "completed",
      summary: "Уточнены стартовый объём, целевая дистанция и ограничения по тренировкам.",
      createdAt: "2026-06-15T08:30:00+03:00",
    },
    {
      id: "session-plan",
      goalId: "goal-ielts",
      type: "plan",
      model: "google/gemini-2.5-flash-lite",
      status: "completed",
      summary: "План разбит на speaking-практику, эссе Writing, словарный запас и mock-экзамен.",
      createdAt: "2026-06-15T09:10:00+03:00",
    },
    {
      id: "session-review",
      goalId: "goal-savings",
      type: "review",
      model: "google/gemini-2.5-flash-lite",
      status: "completed",
      summary: "Подтверждён прогресс по автопереводу; рекомендовано усилить сокращение расходов.",
      createdAt: "2026-06-15T10:20:00+03:00",
    },
  ],
  weeklyReview: {
    weekStart: "2026-06-15",
    summary:
      "Бег вышел на стабильные 15 км в неделю, по IELTS закрыт пробный тест и идёт speaking-практика, подушка безопасности заполнена на 60%.",
    recommendations: [
      "Не наращивать недельный объём бега более чем на 10%.",
      "Добавить отдельный день восстановления между интервалами и длинной.",
      "Начать серию эссе Writing Task 2 — это самая слабая секция IELTS.",
    ],
    risks: [
      "Риск перетренированности при одновременном росте объёма и интенсивности.",
      "Сокращение расходов идёт медленнее автоперевода — резерв может отстать от плана.",
    ],
  },
  knowledgeDocuments: [
    {
      id: "doc-training-log",
      title: "Журнал тренировок (последние 8 недель)",
      source: "manual",
      content:
        "Нед. 1: 12 км. Нед. 4: длинная 12 км. Нед. 6: интервалы 6×400 м. Нед. 8: длинная 15 км — пока самая длинная пробежка. Средний недельный объём растёт примерно на 1 км.",
    },
    {
      id: "doc-budget",
      title: "Личный бюджет — заметки за 3 месяца",
      source: "manual",
      content:
        "Средние месячные расходы — базовая величина для резерва. Крупнейшие категории: аренда, продукты, транспорт. В среднем удаётся откладывать около 20% дохода через автоперевод.",
    },
    {
      id: "doc-ielts-plan",
      title: "План подготовки к IELTS",
      source: "manual",
      content:
        "Фокус на Writing Task 2: структура эссе, связки, академическая лексика. Speaking — два раза в неделю с партнёром. Mock-экзамен за две недели до даты для финальной калибровки.",
    },
  ],
}
