import type { Workspace } from "@/lib/domain"

export const demoWorkspace: Workspace = {
  mode: "demo",
  goals: [
    {
      id: "goal-diploma",
      title: "Диплом OTUS",
      description:
        "Довести FocusTrack AI до рабочего MVP, показать Supabase, OpenRouter, тесты и артефакты защиты.",
      status: "active",
      targetDate: "2026-07-20",
      progressPercent: 83,
      clarifiedContext: {
        audience: "студенты продвинутого курса и IT-специалисты",
        success: "цель уточнена, план создан, прогресс виден, review работает",
      },
    },
    {
      id: "goal-course",
      title: "Домашние задания 3-6",
      description:
        "Подготовить спецификацию, frontend, backend, AI-функции, RAG-эксперимент и отчёты сдачи.",
      status: "active",
      targetDate: "2026-07-05",
      progressPercent: 100,
      clarifiedContext: {
        sequence: "ДЗ 3 → ДЗ 4 → ДЗ 5 → ДЗ 6 → проект",
      },
    },
    {
      id: "goal-rag",
      title: "Knowledge/RAG эксперимент",
      description:
        "Проверить ответы по документам курса и истории прогресса без включения RAG в критический MVP.",
      status: "completed",
      targetDate: "2026-07-12",
      progressPercent: 100,
      clarifiedContext: {
        scope: "лабораторный эксперимент, не обязательная часть core-flow",
      },
    },
  ],
  tasks: [
    {
      id: "task-spec",
      goalId: "goal-diploma",
      title: "Собрать product specification",
      notes: "Описание продукта, user stories, ТЗ и ADR.",
      effort: "M",
      dueDate: "2026-06-18",
      status: "done",
      sortOrder: 10,
    },
    {
      id: "task-ui",
      goalId: "goal-diploma",
      title: "Собрать shadcn dashboard",
      notes: "Рабочий экран целей, задач, AI Review и RAG.",
      effort: "L",
      dueDate: "2026-06-20",
      status: "done",
      sortOrder: 20,
    },
    {
      id: "task-supabase",
      goalId: "goal-diploma",
      title: "Подключить Supabase schema и RLS",
      notes: "Миграции, RLS, restricted grants, cloud push.",
      effort: "L",
      dueDate: "2026-06-22",
      status: "done",
      sortOrder: 30,
    },
    {
      id: "task-openrouter",
      goalId: "goal-diploma",
      title: "Проверить OpenRouter Edge Functions",
      notes: "Ключ в Supabase secrets; AI/RAG endpoints требуют JWT.",
      effort: "M",
      dueDate: "2026-06-24",
      status: "done",
      sortOrder: 40,
    },
    {
      id: "task-video",
      goalId: "goal-diploma",
      title: "Записать Playwright видео и скриншоты",
      notes: "Desktop, mobile, основной happy path.",
      effort: "M",
      dueDate: "2026-06-25",
      status: "done",
      sortOrder: 50,
    },
    {
      id: "task-final-smoke",
      goalId: "goal-diploma",
      title: "Контрольный прогон перед отправкой",
      notes: "Повторить gate, проверить health, 401 без JWT и свежие evidence.",
      effort: "S",
      dueDate: "2026-06-17",
      status: "todo",
      sortOrder: 60,
    },
    {
      id: "task-hw3",
      goalId: "goal-course",
      title: "ДЗ 3: ТЗ, User Stories, UI-концепции",
      notes: "Сформировать папку сдачи и ссылки на продуктовые документы.",
      effort: "M",
      dueDate: "2026-06-18",
      status: "done",
      sortOrder: 10,
    },
    {
      id: "task-hw4",
      goalId: "goal-course",
      title: "ДЗ 4: Frontend MVP",
      notes: "Vite, React, shadcn, локальные сценарии и README.",
      effort: "L",
      dueDate: "2026-06-21",
      status: "done",
      sortOrder: 20,
    },
    {
      id: "task-hw5",
      goalId: "goal-course",
      title: "ДЗ 5: Backend и интеграция",
      notes: "Supabase, RLS, Edge Functions, OpenRouter.",
      effort: "L",
      dueDate: "2026-06-24",
      status: "done",
      sortOrder: 30,
    },
    {
      id: "task-hw6",
      goalId: "goal-course",
      title: "ДЗ 6: аудит и RAG",
      notes: "Security audit, CI, RAG experiment, release notes.",
      effort: "M",
      dueDate: "2026-06-27",
      status: "done",
      sortOrder: 40,
    },
    {
      id: "task-rag-docs",
      goalId: "goal-rag",
      title: "Индексировать документы курса",
      notes: "Минимальный набор: ТЗ, roadmap, weekly reviews.",
      effort: "M",
      dueDate: "2026-06-28",
      status: "done",
      sortOrder: 10,
    },
  ],
  aiSessions: [
    {
      id: "session-clarify",
      goalId: "goal-diploma",
      type: "clarify",
      model: "google/gemini-2.5-flash-lite",
      status: "completed",
      summary: "Сформированы вопросы про аудиторию, дедлайн, критерии защиты.",
      createdAt: "2026-06-17T08:30:00+03:00",
    },
    {
      id: "session-plan",
      goalId: "goal-diploma",
      type: "plan",
      model: "google/gemini-2.5-flash-lite",
      status: "completed",
      summary: "План разбит на ДЗ 3-6, Supabase, Playwright и презентацию.",
      createdAt: "2026-06-17T09:10:00+03:00",
    },
    {
      id: "session-review",
      goalId: "goal-course",
      type: "review",
      model: "google/gemini-2.5-flash-lite",
      status: "completed",
      summary: "Подтверждены Supabase grants, JWT на AI/RAG, Playwright evidence и финальный gate.",
      createdAt: "2026-06-17T10:20:00+03:00",
    },
  ],
  weeklyReview: {
    weekStart: "2026-06-15",
    summary:
      "ДЗ 1 и ДЗ 2 отправлены, ДЗ 3-6 и проектная работа подготовлены локально. Supabase, OpenRouter, тесты и Playwright evidence проверены 17 июня 2026.",
    recommendations: [
      "Отправлять в Otus отдельные ссылки из папок submissions.",
      "На защите показать health=200 и AI endpoint=401 без JWT.",
      "Не раскрывать Supabase/OpenRouter secrets в отчётах и скриншотах.",
    ],
    risks: [
      "Перед публикацией не коммитить локальные .env файлы.",
      "Публичным endpoint оставлен только health; AI/RAG требуют JWT.",
    ],
  },
  knowledgeDocuments: [
    {
      id: "doc-roadmap",
      title: "ROADMAP.md",
      source: "repo",
      content:
        "Этап 3: Product specification. Этап 4: Frontend MVP. Этап 5: Backend and AI functions. Этап 6: Knowledge/RAG experiments.",
    },
    {
      id: "doc-plan",
      title: "FOCUSTRACK_AI_WORK_PLAN.md",
      source: "course",
      content:
        "ДЗ 3-6 и проектная работа подготовлены: спецификация, frontend, backend, security/RAG, Playwright evidence.",
    },
  ],
}
